const IngredientList = [
  { ingredient: "vodka", type: "spirit" },
  { ingredient: "gin", type: "spirit" },
  { ingredient: "sloe gin", type: "spirit" },
  { ingredient: "rum", type: "spirit" },
  { ingredient: "light rum", type: "spirit" },
  { ingredient: "dark rum", type: "spirit" },
  { ingredient: "spiced rum", type: "spirit" },
  { ingredient: "tequila", type: "spirit" },
  { ingredient: "whiskey", type: "spirit" },
  { ingredient: "rye whiskey", type: "spirit" },
  { ingredient: "bourbon", type: "spirit" },
  { ingredient: "scotch", type: "spirit" },
  { ingredient: "absinthe", type: "spirit" },
  { ingredient: "brandy", type: "spirit" },
  { ingredient: "cognac", type: "spirit" },
  { ingredient: "peppermint schnapps", type: "spirit" },
  { ingredient: "peach schnapps", type: "spirit" },
  { ingredient: "applejack", type: "spirit" },
  { ingredient: "sambuca", type: "spirit" },
  { ingredient: "triple sec", type: "liqueur" },
  { ingredient: "blue curacao", type: "liqueur" },
  { ingredient: "cointreau", type: "liqueur" },
  { ingredient: "elderflower liquor", type: "liqueur" },
  { ingredient: "orange liqueur", type: "liqueur" },
  { ingredient: "maraschino liqueur", type: "liqueur" },
  { ingredient: "coffee liqueur", type: "liqueur" },
  { ingredient: "kahlua", type: "liqueur" },
  { ingredient: "creme de menthe", type: "liqueur" },
  { ingredient: "creme de cacao", type: "liqueur" },
  { ingredient: "creme de banane", type: "liqueur" },
  { ingredient: "vermouth", type: "liqueur" },
  { ingredient: "dry vermouth", type: "liqueur" },
  { ingredient: "sweet vermouth", type: "liqueur" },
  { ingredient: "campari", type: "liqueur" },
  { ingredient: "amaretto", type: "liqueur" },
  { ingredient: "irish cream", type: "liqueur" },
  { ingredient: "bailey's irish cream", type: "liqueur" },
  { ingredient: "frangelico", type: "liqueur" },
  { ingredient: "green chartreuse", type: "liqueur" },
  { ingredient: "falernum", type: "liqueur" },
  { ingredient: "grand marnier", type: "liqueur" },
  { ingredient: "bitters", type: "bitters" },
  { ingredient: "angostura bitters", type: "bitters" },
  { ingredient: "orange bitters", type: "bitters" },
  { ingredient: "simple syrup", type: "syrup" },
  { ingredient: "grenadine", type: "syrup" },
  { ingredient: "demerara syrup", type: "syrup" },
  { ingredient: "orgeat", type: "syrup" },
  { ingredient: "lemon juice", type: "juice" },
  { ingredient: "pineapple juice", type: "juice" },
  { ingredient: "apple juice", type: "juice" },
  { ingredient: "lime juice", type: "juice" },
  { ingredient: "orange juice", type: "juice" },
  { ingredient: "grapefruit juice", type: "juice" },
  { ingredient: "cranberry juice", type: "juice" },
  { ingredient: "lemonade", type: "juice" },
  { ingredient: "wine", type: "other" },
  { ingredient: "champagne", type: "other" },
  { ingredient: "lillet blanc", type: "other" },
  { ingredient: "lager", type: "other" },
  { ingredient: "cider", type: "other" },
  { ingredient: "ginger ale", type: "other" },
  { ingredient: "coka-cola", type: "other" },
  { ingredient: "soda water", type: "other" },
  { ingredient: "tonic water", type: "other" },
  { ingredient: "club soda", type: "other" },
  { ingredient: "ginger beer", type: "other" },
  { ingredient: "coffee", type: "other" },
  { ingredient: "cream", type: "other" },
  { ingredient: "heavy cream", type: "other" },
  { ingredient: "light cream", type: "other" },
  { ingredient: "milk", type: "other" },
  { ingredient: "egg white", type: "other" },
  { ingredient: "sugar", type: "other" },
  { ingredient: "brown sugar", type: "other" },
  { ingredient: "honey", type: "other" },
  { ingredient: "nutmeg", type: "other" },
  { ingredient: "olives", type: "other" },
  { ingredient: "maraschino cherry", type: "other" },
  { ingredient: "mint", type: "other" },
  { ingredient: "ice", type: "other" },
];

export default IngredientList;
